spring:
  datasource:
    url:
    username:
    password:
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath*:db/change-log.xml
logging:
  level:
    root: info
  file:
    name:
  logback:
    rollingpolicy:
      max-file-size: 13MB
servlet:
  multipart:
    max-file-size: 5MB
    max-request-size: 5MB
picture:
  upload:
    directory:
contracts:
  upload:
    directory: