spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bank
    username: root
    password: rout
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath*:db/change-log.xml