spring:
  datasource:
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto:
  liquibase:
    change-log:
logging:
  level:
    root:
  file:
    name:
  logback:
    rollingpolicy:
      max-file-size:
servlet:
  multipart:
     max-file-size:
     max-request-size:
bank:
  picture:
    upload:
     directory:
