spring:
  datasource:
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto:
  liquibase:
    change-log:
logging:
  level:
    root:
  file:
    name:
  logback:
    rollingpolicy:
      max-file-size: