spring:
  application:
    name: bank-common
  datasource:
    url: jdbc:mysql://localhost:3306/bank
    username: root
    password: rout
  mail:
    host: smtp.gmail.com
    port: 587
    username: mailsenderforjava@gmail.com
    password: iltifceckjkwsohf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath*:db/change-log.xml
logging:
  level:
    root: info
  file:
    name: C:\\Users\\User\\IdeaProjects\\bank\\logs\\bank-%d{yyyy-MM-dd-HH-mm-ss}.%i.log
  logback:
    rollingpolicy:
      max-file-size: 13MB
servlet:
  multipart:
    max-file-size: 5MB
    max-request-size: 5MB
picture:
  upload:
    directory: ./pictures
contract:
  upload:
    directory: ./contract